steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/domos/cashier-frontend:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'

images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/domos/cashier-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
