"""add_obligations_table

Revision ID: c6068e1a480f
Revises: 
Create Date: 2026-06-21 20:38:19.533092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6068e1a480f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False, comment="Номер на апартамента (напр. '1', '12А')"),
    sa.Column('floor', sa.Integer(), nullable=True, comment='Етаж (0 за партер, отрицателни за сутерен)'),
    sa.Column('owner_name', sa.String(length=200), nullable=False, comment='Име на собственика'),
    sa.Column('residents_count', sa.Integer(), nullable=False, comment='Брой живущи в апартамента'),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Месечна такса в лева'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Допълнителни бележки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Потребителско име за вход'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хеширана парола'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment="Име за показване (напр. 'Цецка')"),
    sa.Column('role', sa.Enum('ADMIN', 'CASHIER', 'VIEWER', name='userrole'), nullable=False, comment='Роля на потребителя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Дали потребителят е активен'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('custom_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False, comment='ID на апартамента'),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False, comment='Дължима сума в лева'),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False, comment='Платена сума в лева'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание на задължението'),
    sa.Column('status', sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='customchargestatus'), nullable=False, comment='Статус на задължението'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_charges_apartment_id'), 'custom_charges', ['apartment_id'], unique=False)
    op.create_table('monthly_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False, comment='ID на апартамента'),
    sa.Column('month', sa.String(length=7), nullable=False, comment='Месец на задължението (YYYY-MM)'),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False, comment='Дължима сума в лева'),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False, comment='Платена сума в лева'),
    sa.Column('status', sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='chargestatus'), nullable=False, comment='Статус на задължението'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_charges_apartment_id'), 'monthly_charges', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_monthly_charges_month'), 'monthly_charges', ['month'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('MONTHLY', 'INITIAL', 'PENALTY', 'REPAIR', 'FUND', 'OTHER', name='obligationtype'), nullable=False, comment='Тип на задължението'),
    sa.Column('apartment_id', sa.Integer(), nullable=False, comment='ID на апартамента'),
    sa.Column('month', sa.String(length=7), nullable=True, comment='Месец на задължението (YYYY-MM), само за месечни такси'),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False, comment='Дължима сума в лева'),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False, comment='Платена сума в лева'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание на задължението'),
    sa.Column('status', sa.Enum('PAID', 'PARTIAL', 'UNPAID', name='obligationstatus'), nullable=False, comment='Статус на задължението'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_apartment_id'), 'obligations', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_obligations_month'), 'obligations', ['month'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_type'), 'obligations', ['type'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False, comment='ID на апартамента'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Платена сума в лева'),
    sa.Column('month', sa.String(length=7), nullable=False, comment='Месец за плащането (YYYY-MM)'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Дата на плащане'),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Метод на плащане (cash, bank, card)'),
    sa.Column('collected_by_id', sa.Integer(), nullable=True, comment='ID на касиера приел плащането'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Допълнителни бележки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_apartment_id'), 'payments', ['apartment_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=False, comment='Номер на разписката (YYYY-NNNNNN)'),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='ID на плащането'),
    sa.Column('is_copy', sa.Boolean(), nullable=False, comment='Дали е копие (True) или оригинал (False)'),
    sa.Column('original_receipt_id', sa.Integer(), nullable=True, comment='ID на оригиналната разписка (само за копия)'),
    sa.Column('issued_at', sa.DateTime(), nullable=False, comment='Дата и час на издаване'),
    sa.Column('issued_by_id', sa.Integer(), nullable=True, comment='ID на потребителя издал разписката'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на създаване'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата на последна промяна'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_receipt_id'], ['receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payments_apartment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_obligations_type'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_month'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_apartment_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_monthly_charges_month'), table_name='monthly_charges')
    op.drop_index(op.f('ix_monthly_charges_apartment_id'), table_name='monthly_charges')
    op.drop_table('monthly_charges')
    op.drop_index(op.f('ix_custom_charges_apartment_id'), table_name='custom_charges')
    op.drop_table('custom_charges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('apartments')
    # ### end Alembic commands ###
